global using System;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using System.Collections.Generic;
global using System.Linq;
global using MicroLog.Collector.Client;
global using MicroLog.Provider.AspNetCore;
global using IMicroLogger = MicroLog.Core.Abstractions.ILogger;