version: '3.4'

services:
  microlog.mongoDb:
    image: mongo
    container_name: microlog.mongoDb
    volumes:
      - logsDb_data:/data/db
    ports:
      - "27017:27017"

  microlog.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: microlog.rabbitmq

  microlog.collector:
    image: ${DOCKER_REGISTRY-}micrologcollector
    container_name: microlog.collector
    build:
      context: .
      dockerfile: MicroLog.Collector/Dockerfile

volumes:
  logsDb_data: