version: '3.4'

services:
  microlog.mongoDb:
    ports:
      - "27017:27017"

  microlog.rabbitmq:
    hostname: rabbit-log-collector
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rabbit-log-collector
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  microlog.collector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "Sinks__Mongo__0__ConnectionString=mongodb://microlog.mongoDb:27017"
      - "Collector__RabbitMq__HostName=rabbit-log-collector"
      - "Collector__RabbitMq__Port=5672"
      - "Collector__RabbitMq__UserName=rabbit"
      - "Collector__RabbitMq__Password=rabbit"
    ports:
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro