version: '3.4'

services:
  microlog.mongoDb:
    image: mongo
    container_name: microlog.mongoDb
    volumes:
      - logsDb_data:/data/db
      - logsDb_config:/data/configdb

  microlog.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: microlog.rabbitmq
    volumes:
      - rabbitMq_data:/var/lib/rabbitmq

  microlog.collector:
    image: ${DOCKER_REGISTRY-}micrologcollector
    container_name: microlog.collector
    build:
      context: .
      dockerfile: MicroLog.Collector/Dockerfile
    depends_on:
      - microlog.rabbitmq
      - microlog.mongoDb

  microlog.publisher:
    image: ${DOCKER_REGISTRY-}micrologcollector
    container_name: microlog.publisher
    build:
      context: .
      dockerfile: MicroLog.Collector/Dockerfile
    depends_on:
      - microlog.rabbitmq
      - microlog.mongoDb

  microlog.lama:
    image: ${DOCKER_REGISTRY-}microloglama
    container_name: microlog.lama
    build:
      context: .
      dockerfile: Microlog.Lama/Server/Dockerfile

volumes:
  logsDb_data:
  logsDb_config:
  rabbitMq_data: